name: Deploy to gh-pages

on: workflow_dispatch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pages
        uses: actions/configure-pages@v5
        id: pages

      - name: Build static
        run: |
          npm ci
          npm run build -- --base=${{steps.pages.outputs.base_path}}

      - name: Upload static files as artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/

  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to gh-pages
        id: deployment
        uses: actions/deploy-pages@v4
